source 'https://rubygems.org'

gem 'rest-client', '~> 1.7.3'
gem 'rspec'
gem 'yard', '~> 0.9.11'
gem 'gemcutter'
gem 'pry'
gem 'pry-doc'
gem 'vcr'
gem 'webmock',  '~> 1.15.2'
gem 'simplecov'
gem 'redcarpet'
gem 'rake'
